add EntriesController and ReviewsController for HTTP method mappings
PeerRequest/PeerRequest pull request #10
Opened 2023-01-18 18:36 UTC by veropossumus

2023-01-19 19:09 UTC, ToastOfToastyness commented on src/main/java/com/peerrequest/app/api/EntriesController.java
>          return mockEntry();
You set the author and title of updatedEntry and then return mockEntry?
Why?

2023-01-19 20:25 UTC, Wil-Lee requested changes
You find examples in BiddingProcessesController and RequestsController to fix the issues

2023-01-19 20:25 UTC, Wil-Lee commented on src/main/java/com/peerrequest/app/api/EntriesController.java
> +        return mockEntry();
should return the entry of the request body

2023-01-19 20:25 UTC, Wil-Lee commented on src/main/java/com/peerrequest/app/api/EntriesController.java
> +        return updatedEntry;
doesn't update the hardcoded entry. Maybe updating the hardcoded entry is not needed. Evaluate by yourself.

2023-01-19 20:25 UTC, Wil-Lee commented on src/main/java/com/peerrequest/app/api/ReviewsController.java
> +        return mockReview();
Should return the review in the requestBody

2023-01-19 20:25 UTC, Wil-Lee commented on src/main/java/com/peerrequest/app/api/ReviewsController.java
> +        return mockReview().getReviewDocument();
should replace the reviewDocument of the hardcoded review

2023-01-19 20:25 UTC, Wil-Lee commented on src/main/java/com/peerrequest/app/api/ReviewsController.java
> +        return updatedReview;
doesn't update the hardcoded review. Maybe updating the hardcoded review is not needed. Evaluate by yourself.

2023-01-24 22:46 UTC, bits0rcerer commented
Before merging we should wait for #28.

I think I will do #28 tomorrow and then we will see if our endpoints work as intended and return the correct JSON. :crossed_fingers:

2023-01-26 16:57 UTC, Wil-Lee submitted a review, later dismissed

2023-01-30 18:44 UTC, Wil-Lee approved these changes

2023-01-30 18:48 UTC, merged