11 user controller endpoint
PeerRequest/PeerRequest pull request #22
Opened 2023-01-20 09:04 UTC by ToastOfToastyness

2023-01-20 17:30 UTC, Wil-Lee requested changes
Same here. Initialize all lokal mockUps in a constructor with zero parameters first. All mockUps will be Null with this implementation

2023-01-20 17:49 UTC, Wil-Lee approved these changes

2023-01-24 22:52 UTC, bits0rcerer requested changes
Some endpoints under `/users` are missing.

2023-01-24 22:52 UTC, bits0rcerer commented on src/main/java/com/peerrequest/app/api/UserController.java
> +    @GetMapping(value = "/users/{userId}/reviews", produces = "application/json")
Not defined in our [API](https://peerrequest.github.io/api_spec/#tag/users)

2023-01-26 16:55 UTC, Wil-Lee approved these changes

2023-01-30 18:06 UTC, closed without merging

2023-01-30 18:13 UTC, Wil-Lee commented
I wasn't able to merge/rebase this branch with the master (mergeConflictLoop goes brrrrr), so I decided to create a new branch and start a pull request from there